/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseIcon: typeof import('./src/components/atoms/BaseIcon.vue')['default']
    ListCourse: typeof import('./src/components/organisms/Home/ListCourse.vue')['default']
    ListMyCourse: typeof import('./src/components/organisms/Home/ListMyCourse.vue')['default']
    ListTeacher: typeof import('./src/components/organisms/Home/ListTeacher.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCarousel: typeof import('./src/components/organisms/Home/TheCarousel.vue')['default']
    TheCategory: typeof import('./src/components/organisms/Home/TheCategory.vue')['default']
    TheFooter: typeof import('./src/components/organisms/Standard/TheFooter.vue')['default']
    TheHeader: typeof import('./src/components/organisms/Standard/TheHeader.vue')['default']
    UserLogin: typeof import('./src/components/organisms/UserLogin.vue')['default']
    UserSignUp: typeof import('./src/components/organisms/UserSignUp.vue')['default']
  }
}
